import { Workshop } from '../types/workshop';

export const workshops: Record<string, Workshop> = {
    // --- TPE WEB WORKSHOPS ---
    'transaction-flow': {
        id: 'transaction-flow',
        title: 'Transaction Flow',
        description: 'Understand the complete lifecycle of a payment transaction from Terminal to Issuer.',
        category: 'tpe',
        difficulty: 'beginner',
        durationMinutes: 15,
        theory: {
            sections: [
                {
                    title: 'The 4 Key Players',
                    content: 'A card transaction involves: Cardholder, Merchant (Acquirer), Network (Scheme), and Issuer (Bank). The Terminal (TPE) initiates the flow.',
                    diagram: 'four-party-model'
                },
                {
                    title: 'Steps: Auth vs Clearing',
                    content: 'Authorization happens in real-time to reserve funds. Clearing & Settlement happens in batches later (usually T+1).',
                }
            ]
        },
        exercise: {
            type: 'timeline',
            description: 'Order the transaction steps correctly.',
            steps: [
                { id: 's1', instruction: 'Card Insertion', type: 'action' },
                { id: 's2', instruction: 'PIN Entry', type: 'input' },
                { id: 's3', instruction: 'Online Request', type: 'action' },
                { id: 's4', instruction: 'Issuer Approval', type: 'verification' }
            ]
        },
        quiz: {
            questions: [
                {
                    id: 'q1',
                    text: 'Who approves the transaction funds?',
                    options: ['The Merchant', 'The Network (Visa/MC)', 'The Issuer Bank', 'The Terminal'],
                    correctIndex: 2,
                    explanation: 'Only the Issuer Bank holds the user funds and can approve the transaction.'
                }
            ]
        }
    },
    'iso8583': {
        id: 'iso8583',
        title: 'ISO 8583 Anatomy',
        description: 'Deep dive into the standard messaging format for card transactions.',
        category: 'tpe',
        difficulty: 'intermediate',
        durationMinutes: 20,
        theory: {
            sections: [
                {
                    title: 'Structure',
                    content: 'MTI (Message Type Indicator) + Bitmap + Data Elements.',
                    code: '0100 (Auth Request) | Primary Bitmap | DE2 (PAN) | DE3 (Proc Code) ...'
                }
            ]
        },
        exercise: {
            type: 'decoder',
            description: 'Decode the MTI 0110.',
        },
        quiz: {
            questions: [
                {
                    id: 'q1',
                    text: 'What does 0200 stand for?',
                    options: ['Authorization Request', 'Financial Transaction Request', 'Network Management', 'Reversal'],
                    correctIndex: 1,
                    explanation: '0200 is for Financial Transactions (posted immediately), unlike 0100 (Auth only).'
                }
            ]
        }
    },
    'emv-chip': {
        id: 'emv-chip',
        title: 'EMV Chip Flow',
        description: 'How chip cards authenticate and secure data using crypto.',
        category: 'tpe',
        difficulty: 'advanced',
        durationMinutes: 25,
        theory: {
            sections: [{ title: 'ARQC generation', content: 'Application Request Cryptogram is generated by the card key.' }]
        },
        exercise: { type: 'simulation', description: 'Simulate a chip read.' },
        quiz: { questions: [{ id: 'q1', text: 'What prevents card cloning?', options: ['The PIN', 'The Dynamic ARQC', 'The Magstripe'], correctIndex: 1, explanation: 'The chip generates a unique cryptogram (ARQC) for every transaction.' }] }
    },
    'replay-attack': {
        id: 'replay-attack',
        title: 'Replay Attacks',
        description: 'Detecting and preventing transaction replay.',
        category: 'tpe',
        difficulty: 'intermediate',
        durationMinutes: 15,
        theory: {
            sections: [{ title: 'The Attack', content: 'An attacker records a valid message and sends it again later.' }]
        },
        exercise: { type: 'defense', description: 'Spot the replayed packet.' },
        quiz: { questions: [{ id: 'q1', text: 'Which field prevents replays?', options: ['PAN', 'STAN (Trace Audit Number)', 'Amount', 'Currency'], correctIndex: 1, explanation: 'STAN must be unique per transaction for a given terminal.' }] }
    },

    // --- WALLET WORKSHOPS ---
    '3ds-flow': {
        id: '3ds-flow',
        title: '3D-Secure 2.0',
        description: 'Frictionless vs Challenge flows in e-commerce.',
        category: 'wallet',
        difficulty: 'beginner',
        durationMinutes: 15,
        theory: { sections: [{ title: 'Data Sharing', content: 'Merchant sends device data to Issuer to assess risk.' }] },
        exercise: { type: 'flow', description: 'Complete a Challenge flow.' },
        quiz: { questions: [{ id: 'q1', text: 'What triggers a Challenge?', options: ['Different shipping address', 'High Risk Score', 'Buying shoes', 'Night time'], correctIndex: 1, explanation: 'The ACS (Access Control Server) decides based on risk analysis.' }] }
    },
    'cvv-validation': {
        id: 'cvv-validation',
        title: 'CVV/CVC Logic',
        description: 'How the 3-digit code verifies card presence.',
        category: 'wallet',
        difficulty: 'intermediate',
        durationMinutes: 10,
        theory: { sections: [{ title: 'Calcul', content: 'DES(PAN + ExpDate + ServiceCode, CVK)' }] },
        exercise: { type: 'calc', description: 'Verify a CVV.' },
        quiz: { questions: [{ id: 'q1', text: 'Is CVV stored in the chip?', options: ['Yes', 'No, it is iCVV', 'No, it is only on stripe'], correctIndex: 1, explanation: 'The chip uses iCVV (different code) to prevent stripe cloning.' }] }
    },
    'fraud-patterns': {
        id: 'fraud-patterns',
        title: 'Fraud Patterns',
        description: 'Recognizing common fraud scenarios.',
        category: 'wallet',
        difficulty: 'beginner',
        durationMinutes: 20,
        theory: { sections: [{ title: 'Velocity', content: 'Too many transactions in short time.' }] },
        exercise: { type: 'analysis', description: 'Flag the suspicious transaction.' },
        quiz: { questions: [{ id: 'q1', text: 'What is "Velocity"?', options: ['Speed of network', 'Transaction frequency', 'Card delivery speed'], correctIndex: 1, explanation: 'High frequency indicates possible card theft.' }] }
    },

    // --- HSM ADMIN WORKSHOPS ---
    'pin-block': {
        id: 'pin-block',
        title: 'PIN Block Formats',
        description: 'ISO-0, ISO-1, ISO-3 encoded PIN blocks.',
        category: 'hsm',
        difficulty: 'advanced',
        durationMinutes: 30,
        theory: { sections: [{ title: 'ISO-0', content: 'XORs the PIN with the PAN.' }] },
        exercise: { type: 'encoding', description: 'Encode a PIN Block.' },
        quiz: { questions: [{ id: 'q1', text: 'Which format requires the PAN?', options: ['ISO-0', 'ISO-1', 'ISO-2'], correctIndex: 0, explanation: 'ISO-0 binds the PIN to the PAN for security.' }] }
    },
    'mac-calculation': {
        id: 'mac-calculation',
        title: 'MAC Integrity',
        description: 'Message Authentication Codes explanation.',
        category: 'hsm',
        difficulty: 'advanced',
        durationMinutes: 25,
        theory: { sections: [{ title: 'Purpose', content: 'Detect if data changed in transit.' }] },
        exercise: { type: 'calc', description: 'Generate a MAC.' },
        quiz: { questions: [{ id: 'q1', text: 'Diff betwen Hash and MAC?', options: ['None', 'MAC uses a Key', 'Hash is shorter'], correctIndex: 1, explanation: 'MAC requires a secret key, Hash does not.' }] }
    },
    'key-hierarchy': {
        id: 'key-hierarchy',
        title: 'Key Hierarchy',
        description: 'LMK, ZMK, TMK, ZPK relationships.',
        category: 'hsm',
        difficulty: 'intermediate',
        durationMinutes: 20,
        theory: { sections: [{ title: 'Master Keys', content: 'LMK protects local keys. ZMK protects zone keys.' }] },
        exercise: { type: 'diagram', description: 'Map the keys.' },
        quiz: { questions: [{ id: 'q1', text: 'What encrypts the PIN in transit?', options: ['LMK', 'ZMK', 'ZPK (Zone PIN Key)'], correctIndex: 2, explanation: 'ZPK is the working key for PINs between nodes.' }] }
    }
};
