openapi: 3.0.3
info:
  title: crypto-service API
  description: Service d'opérations cryptographiques
  version: 1.0.0

servers:
  - url: http://localhost:8010

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy

  /encrypt:
    post:
      summary: Chiffrer données
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [data, key]
              properties:
                data:
                  type: string
                  description: Données à chiffrer
                key:
                  type: string
                  description: Clé en hexadécimal
                algorithm:
                  type: string
                  enum: [aes-128-cbc, aes-256-cbc, des-cbc, des-ede3-cbc]
      responses:
        '200':
          description: Données chiffrées

  /decrypt:
    post:
      summary: Déchiffrer données
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [data, key]
              properties:
                data:
                  type: string
                key:
                  type: string
                algorithm:
                  type: string
      responses:
        '200':
          description: Données déchiffrées

  /mac/generate:
    post:
      summary: Générer MAC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [data, key]
              properties:
                data:
                  type: string
                key:
                  type: string
                algorithm:
                  type: string
                  enum: [sha256, sha1, md5]
      responses:
        '200':
          description: MAC généré

  /mac/verify:
    post:
      summary: Vérifier MAC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [data, mac, key]
              properties:
                data:
                  type: string
                mac:
                  type: string
                key:
                  type: string
      responses:
        '200':
          description: Résultat vérification

  /pin/encode:
    post:
      summary: Encoder PIN Block (ISO 9564)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [pin, pan]
              properties:
                pin:
                  type: string
                  minLength: 4
                  maxLength: 12
                pan:
                  type: string
                format:
                  type: integer
                  enum: [0, 1, 3]
                  description: |
                    Format ISO 9564:
                    - 0: PIN XOR PAN
                    - 1: PIN avec padding aléatoire
                    - 3: Format 3 (sans PAN)
      responses:
        '200':
          description: PIN Block généré
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: string
                    description: PIN Block hex (16 chars)
                  _educational:
                    type: object

  /cvv/generate:
    post:
      summary: Générer CVV
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [pan, expiry]
              properties:
                pan:
                  type: string
                expiry:
                  type: string
                  example: "1228"
                serviceCode:
                  type: string
                  default: "101"
      responses:
        '200':
          description: CVV généré
